import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const distDir = join(root, "dist");

const data = {
  buildHash: "BOOM-ORCH-0001",
  milestones: [
    { label: "Scope mapped", detail: "42 modules", status: "complete" },
    { label: "Queue drafted", detail: "06 tasks", status: "complete" },
    { label: "Run staged", detail: "0 blockers", status: "active" },
    { label: "Artifacts ready", detail: "dist/index.html", status: "ready" },
  ],
  signals: [
    { label: "Coverage", value: "92%", delta: "+4%" },
    { label: "Latency", value: "1.8s", delta: "-0.4s" },
    { label: "Changes", value: "14 files", delta: "+2" },
    { label: "Queue depth", value: "06", delta: "steady" },
  ],
  tasks: [
    {
      id: "task-00",
      title: "Map fixture entry points",
      status: "ready",
      files: ["src/index.ts", "src/styles.css"],
    },
    {
      id: "task-01",
      title: "Define build targets",
      status: "ready",
      files: ["package.json", "scripts/build.js"],
    },
    {
      id: "task-02",
      title: "Generate HTML shell",
      status: "ready",
      files: ["dist/index.html"],
    },
    {
      id: "task-03",
      title: "Paint visual system",
      status: "active",
      files: ["dist/styles.css"],
    },
    {
      id: "task-04",
      title: "Wire dynamic cards",
      status: "ready",
      files: ["dist/app.js"],
    },
    {
      id: "task-05",
      title: "Verify build output",
      status: "ready",
      files: ["scripts/verify.js"],
    },
  ],
};

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Boomerang Fixture</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <div class="page">
      <header class="hero">
        <div class="hero__content">
          <p class="eyebrow">Boomerang Fixture</p>
          <h1>Orbit Build Report</h1>
          <p class="lede">
            A small deterministic site for validating workflow output.
          </p>
          <div class="pill-row">
            <span class="pill">Queue: 06 tasks</span>
            <span class="pill">Build: Stable</span>
            <span class="pill">Target: dist/</span>
          </div>
        </div>
        <div class="hero__panel" id="score-panel"></div>
      </header>

      <section class="grid">
        <div class="card">
          <h2>Milestones</h2>
          <ul id="milestones"></ul>
        </div>
        <div class="card">
          <h2>Signals</h2>
          <div class="metrics" id="signals"></div>
        </div>
      </section>

      <section class="tasks">
        <div class="section-header">
          <h2>Queue Preview</h2>
          <p>Work items created by the planner.</p>
        </div>
        <div class="task-grid" id="task-grid"></div>
      </section>

      <footer class="footer">
        <div>Generated by boomerang fixture build.</div>
        <div class="footer__hash" id="build-hash"></div>
      </footer>
    </div>
    <script src="app.js"></script>
  </body>
</html>
`;

const css = `:root {
  color-scheme: light;
  --bg: #0c111c;
  --panel: #121a2b;
  --panel-strong: #19233a;
  --text: #e6ebf4;
  --muted: #97a3b8;
  --accent: #6be3a6;
  --accent-2: #6aa9ff;
  --warn: #f1c270;
  --border: #26324a;
  --shadow: 0 20px 40px rgba(7, 12, 23, 0.35);
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: "IBM Plex Sans", "Segoe UI", Tahoma, sans-serif;
  background: radial-gradient(circle at top, #1b2340, #0a0f1c);
  color: var(--text);
}

.page {
  max-width: 1100px;
  margin: 0 auto;
  padding: 48px 24px 72px;
}

.hero {
  display: grid;
  grid-template-columns: 2fr 1fr;
  gap: 32px;
  background: linear-gradient(135deg, #11192b, #0f1524);
  border: 1px solid var(--border);
  border-radius: 24px;
  padding: 32px;
  box-shadow: var(--shadow);
}

.hero__content h1 {
  margin: 12px 0 8px;
  font-size: 36px;
}

.eyebrow {
  text-transform: uppercase;
  letter-spacing: 0.2em;
  font-size: 12px;
  color: var(--accent);
  margin: 0;
}

.lede {
  color: var(--muted);
  max-width: 520px;
}

.pill-row {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 20px;
}

.pill {
  border: 1px solid var(--border);
  border-radius: 999px;
  padding: 6px 14px;
  font-size: 13px;
  background: rgba(18, 26, 43, 0.7);
}

.hero__panel {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 20px;
  padding: 20px;
  display: grid;
  align-content: center;
  gap: 12px;
}

.score {
  display: grid;
  gap: 8px;
}

.score__value {
  font-size: 44px;
  font-weight: 600;
  color: var(--accent-2);
}

.score__label {
  color: var(--muted);
}

.grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 24px;
  margin-top: 32px;
}

.card {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 20px;
  padding: 20px;
  box-shadow: var(--shadow);
}

.card h2 {
  margin: 0 0 16px;
  font-size: 18px;
}

#milestones {
  list-style: none;
  padding: 0;
  margin: 0;
  display: grid;
  gap: 12px;
}

.milestone {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 10px 14px;
  background: var(--panel-strong);
}

.milestone__title {
  font-weight: 500;
}

.milestone__detail {
  color: var(--muted);
  font-size: 13px;
}

.milestone--complete {
  border-color: rgba(107, 227, 166, 0.4);
}

.milestone--active {
  border-color: rgba(106, 169, 255, 0.5);
}

.milestone--ready {
  border-color: rgba(241, 194, 112, 0.5);
}

.metrics {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}

.metric {
  border: 1px solid var(--border);
  border-radius: 14px;
  padding: 14px;
  background: var(--panel-strong);
}

.metric__label {
  color: var(--muted);
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.metric__value {
  font-size: 20px;
  margin-top: 6px;
}

.metric__delta {
  font-size: 12px;
  color: var(--accent);
}

.tasks {
  margin-top: 32px;
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  gap: 12px;
}

.section-header p {
  color: var(--muted);
  margin: 0;
}

.task-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 18px;
  margin-top: 20px;
}

.task-card {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 16px;
  padding: 16px;
  display: grid;
  gap: 10px;
}

.task-card__id {
  font-size: 12px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--muted);
}

.task-card__title {
  font-size: 16px;
  font-weight: 600;
}

.task-card__status {
  font-size: 12px;
  padding: 4px 10px;
  border-radius: 999px;
  width: fit-content;
  background: rgba(255, 255, 255, 0.06);
}

.task-card__status--active {
  color: #121a2b;
  background: var(--accent-2);
}

.task-card__status--ready {
  color: #121a2b;
  background: var(--accent);
}

.task-card__files {
  color: var(--muted);
  font-size: 12px;
  line-height: 1.4;
}

.footer {
  margin-top: 36px;
  display: flex;
  justify-content: space-between;
  color: var(--muted);
  font-size: 12px;
}

.footer__hash {
  color: var(--accent);
}

@media (max-width: 900px) {
  .hero {
    grid-template-columns: 1fr;
  }

  .grid {
    grid-template-columns: 1fr;
  }

  .task-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 640px) {
  .task-grid {
    grid-template-columns: 1fr;
  }
}
`;

const js = `const data = ${JSON.stringify(data, null, 2)};

const byId = (id) => document.getElementById(id);

const scorePanel = byId("score-panel");
const milestonesEl = byId("milestones");
const signalsEl = byId("signals");
const taskGrid = byId("task-grid");
const buildHashEl = byId("build-hash");

const scoreLabel = document.createElement("div");
scoreLabel.className = "score";
const scoreValue = document.createElement("div");
scoreValue.className = "score__value";
scoreValue.textContent = String(data.tasks.length);
const scoreText = document.createElement("div");
scoreText.className = "score__label";
scoreText.textContent = "Tasks in queue";
scoreLabel.append(scoreValue, scoreText);
scorePanel.append(scoreLabel);

data.milestones.forEach((item) => {
  const li = document.createElement("li");
  li.className = "milestone milestone--" + item.status;
  const title = document.createElement("span");
  title.className = "milestone__title";
  title.textContent = item.label;
  const detail = document.createElement("span");
  detail.className = "milestone__detail";
  detail.textContent = item.detail;
  li.append(title, detail);
  milestonesEl.append(li);
});

data.signals.forEach((metric) => {
  const card = document.createElement("div");
  card.className = "metric";
  const label = document.createElement("div");
  label.className = "metric__label";
  label.textContent = metric.label;
  const value = document.createElement("div");
  value.className = "metric__value";
  value.textContent = metric.value;
  const delta = document.createElement("div");
  delta.className = "metric__delta";
  delta.textContent = metric.delta;
  card.append(label, value, delta);
  signalsEl.append(card);
});

data.tasks.forEach((task) => {
  const card = document.createElement("div");
  card.className = "task-card";
  const id = document.createElement("div");
  id.className = "task-card__id";
  id.textContent = task.id;
  const title = document.createElement("div");
  title.className = "task-card__title";
  title.textContent = task.title;
  const status = document.createElement("div");
  status.className = "task-card__status task-card__status--" + task.status;
  status.textContent = task.status.toUpperCase();
  const files = document.createElement("div");
  files.className = "task-card__files";
  files.textContent = "Files: " + task.files.join(", ");
  card.append(id, title, status, files);
  taskGrid.append(card);
});

buildHashEl.textContent = "Build hash: " + data.buildHash;
`;

await mkdir(distDir, { recursive: true });
await Promise.all([
  writeFile(join(distDir, "index.html"), html, "utf8"),
  writeFile(join(distDir, "styles.css"), css, "utf8"),
  writeFile(join(distDir, "app.js"), js, "utf8"),
]);
